python sample_generation.py \
    --profiles-path <profiles.jsonl> \
    --event-sequences-path <events.jsonl> \
    --query-database-path <queries.jsonl> \
    --output-path <output.jsonl> \
    --model-name <model> \
    --model-api-key <key> \
    --model-path <path> \
    --model-url <url> \
    --use-vllm \
    --max-conv-turns <n> \
    --max-events-number <n> \
    --max-profiles <n> \
    --random-state <n> \
    --seed <n> \
    --retriever-model-name <name> \
    --retriever-collection-name <name> \
    --retriever-embedding-dim <dim> \
    --retriever-persist-dir <dir> \
    --retriever-distance <cosine|l2|ip> \
    --retriever-device <cpu|cuda> \
    --retriever-use-custom-embeddings \
    --retriever-text-field <field> \
    --retriever-id-field <field> \
    --retriever-batch-size <n> \
    --max-retrievals <n>
